### ISSUE TITLE
Add Optional Geo-location property to DataElement

### ISSUE THREAD

**Issue by Purg** [Kitware/SMQTK#237]
Some data elements may be geo-tagged. If we can optionally carry that as a property on data elements, this can enable geo-location-based features in SMQTK, e.g. geographic visualization / filtering.

**Comment by aashish24** [comment]
:+1:

**Comment by Purg** [comment]
This feature has been out of scope for a long time, so I'm going to close this issue.  If we want to address this releationship again in the future, it should probably not be solved by encapsulation buy by another structure.  The recent addition of key-value-store interface/implementation would fit the bill.
