### ISSUE TITLE
Document differences in custom libsvm distribution

### ISSUE THREAD

**Issue by danlamanna** [Kitware/SMQTK#284]
Ideally we could get an actual diff against the revision the code was based off of.

**Comment by Purg** [comment]
Valid. The only difference that I know of is that it provides another mode that uses histogram intersection kernel. @z-harry-sun provided me this particular version so he would know best the differences between his custom version and upstream.

**Comment by danlamanna** [comment]
@Purg Is this issue the main blocker from being able to `pip install smqtk` and have full access to functionality? (Instead of relying on CMake for installing).

**Comment by Purg** [comment]
One of them (this libsvm is effectively required for the currently only implementation of the RelevancyIndex interface required for IQR).

**Comment by danlamanna** [comment]
What are the others? Is there consensus that we should be aiming for a world where `pip install smqtk` just works™? @wphicks

**Comment by Purg** [comment]
I believe that would be optimal and can already be done.  Its just the case that not all plugins provided within SMQTK would be usable without other optional dependencies, some being harder to acquire, being installed by the user (like FLANN and libSVM).  There technically already is a pip-installable SMQTK up on pypi (though that's somewhat experimental and around the 0.6.2 version).

Somewhere in here I or someone needs to document the official release process for SMQTK (bumping version, swapping release notes, etc.) to which we can add things like uploading a new version to pypi and maybe get crazy with docker containers to dockerhub.

**Comment by Purg** [comment]
The ideal state however is that in the raw form of SMQTK, there be at least one implementation for every algorithm/representation interface, which is currently not the case.
