### ISSUE TITLE
Step by step instructions for computing an image feature set with the python library in README

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/SMQTK#33]
Something like this (ok it will not look exactly like this but something similarly straightforward):

```python
import smqtk

img = smqtk.load('myimage.png')
feature = img.get_feature('feature name')
print feature
```

In the README I see stuff about config files, etc. for setting up batch file ingests, but it seems something simple like the script above should be possible.

**Comment by Purg** [comment]
:+1: A bit of that is going to have to change with what basically amounts to an overhaul that I'm working on, which includes more formal data element/set abstractions and some other stuff. But yes, this should happen. Definitely not going to be that simple, sadly. :3

**Comment by Purg** [comment]
Does the commit addressing this issue help?

**Comment by Purg** [comment]
Bump.

**Comment by Purg** [comment]
Going to close this for now. If there is further progress required/to be made, a new issues can be opened.
