### ISSUE TITLE
Consider using concurrent.futures in place of smqtk.utils.parallel

### ISSUE THREAD

**Issue by danlamanna** [Kitware/SMQTK#343]
For Python >=2.6, <3 the [backport of futures](https://pypi.org/project/futures/) can be used, otherwise the built in support for Python >=3.2 can be used.

**Comment by Purg** [comment]
In a lot of cases I agree with this.  There is still a possible niche application of the ``smqtk.utils.parallel.parallel_map`` in that it can parallelize the execution of on-the-fly functions and lambda expressions.  I grant that this is less common.
