### ISSUE TITLE
Segfault when loading saved SkLearnBallTreeHashIndex

### ISSUE THREAD

**Issue by neal-siekierski** [Kitware/SMQTK#369]
When using the recently released version 0.20.0 of scikit-learn, loading a saved `SkLearnBallTreeHashIndex` results in a segmentation fault. I can reproduce this by running one of the tests:
```
$ python -m unittest smqtk.tests.algorithms.nn_index.hash_index.test_balltree.TestBallTreeHashIndex.test_load_model
```

The issue seems to be caused by the interaction between a change in how `BallTree`s are pickled (https://github.com/scikit-learn/scikit-learn/pull/11774 &ndash; in short, another attribute has been added to the state) and how `SkLearnBallTreeHashIndex` picks apart and reassembles the `BallTree`'s internal state, with the call to `__setstate__` being what crashes:
https://github.com/Kitware/SMQTK/blob/bcc537856d6b6db0b42b334cd77e2502df609d3c/python/smqtk/algorithms/nn_index/hash_index/sklearn_balltree.py#L141-L153
https://github.com/Kitware/SMQTK/blob/bcc537856d6b6db0b42b334cd77e2502df609d3c/python/smqtk/algorithms/nn_index/hash_index/sklearn_balltree.py#L171-L179

**Comment by Purg** [comment]
This should be fixed as of #375
