### ISSUE TITLE
ImageSpace: Extraneous scrollbars under each image

### ISSUE THREAD

**Issue by wmburke** [Kitware/SMQTK#61]
Under each image, there is a div that holds the icons. It has scroll bars with nothing to scroll. This can be fixed by setting overflow:auto or deleting the overflow tag set on .im-caption in imagespace.min.css on line 38.

This appears in Firefox 38.0 on Ubuntu 15.04.

**Comment by jeffbaumes** [comment]
I made this change though this does not happen on Mac Firefox 38.0.5. I've deployed this change. Let me know if you still see a problem.

**Comment by wmburke** [comment]
Nope - it all looks better! Thanks.
