### ISSUE TITLE
ImageSpace: Image Size link produces no results

### ISSUE THREAD

**Issue by wmburke** [Kitware/SMQTK#62]
When I click on a dot in the Image Size Distribution graph, I get no results. The dot shouldn't show up if there are no results associated with it.

To reproduce:
1. Open ImageSpace, click in search bar (keep the *) and hit enter to bring up all images.
2. The first image (id: /data/roxyimages/cmuImages/Illinois_2012_11_12_1352748331000_6_0.jpg) is a woman in a green Vancouver t-shirt laying on her back. Open the details and click Find Similar Images.
3. When the results load, click Image Size Distribution in the left side bar.
4. Click the dot at width = 149, height = 166. This should probably have 4 results, according to its size.
5. See that it returns no results.

**Comment by jeffbaumes** [comment]
@wmburke this fix is in the deployed version. Let me know if the issue persists. Some parentheses in the search string seem to fix this.

**Comment by wmburke** [comment]
Thanks, Jeff. Looks good.
