### ISSUE TITLE
ImageSpace: Minor interface tweaks

### ISSUE THREAD

**Issue by wmburke** [Kitware/SMQTK#63]
I think these should be simple and can be handled with text and/or html, so I'm grouping them together:

1. A button to show all images. It's not too bad to click in the search bar and then hit enter, unless you're coming from a page that already has the search field populated. Then you have to remember how to do it.
2. A note on the Image Size Distribution and Serial Number Distribution graphs that says that they are only showing results from the current search.
3. If there are no results from the current search for these two graphs, let's say that: "No results found for current search terms." As it is, it's just a bit confusing.

**Comment by jeffbaumes** [comment]
See https://github.com/memex-explorer/image_space/issues/27
