### ISSUE TITLE
ImageSpace: how do you show the full size image?

### ISSUE THREAD

**Issue by wmburke** [Kitware/SMQTK#64]
Previously clicking on the image would open it full size in a new browser window. Now, it doesn't seem possible to see the full size image at all.

I think this is important, especially if you're trying to see if it's the same person in two images - or get a better look at a tattoo, etc...

I would suggest another icon under the images (maybe the picture icon?) that when clicked opens it full size. This could be a browser window for now, but we should probably think about adding light box style functionality so that you could actually move through the images like you do through any web gallery.

**Comment by jeffbaumes** [comment]
See https://github.com/memex-explorer/image_space/issues/26
