### ISSUE TITLE
ImageSpace: missing ads db data??

### ISSUE THREAD

**Issue by wmburke** [Kitware/SMQTK#66]
This may just be me being confused, but when I look at images such as this one:
id:"/data/roxyimages/5070f670039e500755fe7887d6f3d4a8f24e4a79.jpg"
I don't see an ad ID or the text from the ad that it was retrieved from.

Am I missing something or is something amiss?

**Comment by jeffbaumes** [comment]
We have ads_id and ad_url for about 2M of the 30M images at this point, with a few million more coming online by the demo. I have searches to demonstrate the ad ids we currently have available. When that is complete, I'll do a second join which will add in the ad text. So full ad text search won't be there for Wednesday.
